parameters:
    base.service.class: BaseBundle\Base\BaseService
    base.storage.class: BaseBundle\Base\BaseStorage
    base.type.class: BaseBundle\Base\BaseType
    base.twig_extension.class: BaseBundle\Base\BaseTwigExtension
    base.voter.class: BaseBundle\Base\BaseVoter

services:

    base.service:
        class: '%base.service.class%'
        abstract: true
        calls:
          - [setContainer, ["@service_container"]]

    base.storage:
        class: '%base.storage.class%'
        abstract: true
        calls:
          - [setConnection, ["@doctrine.dbal.default_connection"]]

    base.type:
        class: '%base.type.class%'
        abstract: true
        calls:
          - [setContainer, ["@service_container"]]

    base.twig_extension:
        class: '%base.twig_extension.class%'
        abstract: true
        calls:
          - [setContainer, ["@service_container"]]

    base.voter:
        class: '%base.voter.class%'
        abstract: true
        public: false
        calls:
          - [setContainer, ["@service_container"]]
          - [setDecisionManager, ["@security.access.decision_manager"]]
