parameters:
    base.ckeditor.type.class: BaseBundle\Form\Type\CKEditorType
    base.toggle.type.class: BaseBundle\Form\Type\ToggleType

services:

    base.ckeditor.type:
        class: '%base.ckeditor.type.class%'
        parent: base.type
        tags:
            - { name: form.type }

    base.toggle.type:
        class: '%base.toggle.type.class%'
        parent: base.type
        tags:
            - { name: form.type }
