parameters:
    base.incomplete_profile.listener.class: BaseBundle\EventListener\IncompleteProfileListener
    base.last_route.listener.class: BaseBundle\EventListener\LastRouteListener
    base.locale.listener.class: BaseBundle\EventListener\LocaleListener
    base.toggle.listener.class: BaseBundle\EventListener\ToggleListener

services:

    base.incomplete_profile.listener:
        class: '%base.incomplete_profile.listener.class%'
        parent: base.service
        tags:
            - { name: kernel.event_subscriber }

    base.last_route.listener:
        class: '%base.last_route.listener.class%'
        arguments:
            - '@base.routing.helper'
        tags:
            - { name: kernel.event_subscriber }

    base.locale.listener:
        class: '%base.locale.listener.class%'
        arguments:
            - '%kernel.default_locale%'
        tags:
            - { name: kernel.event_subscriber }

    base.toggle.listener:
        class: '%base.toggle.listener.class%'
        parent: base.service
        tags:
            - { name: kernel.event_subscriber }
