parameters:
    base.incomplete_profile.service.provider.class: BaseBundle\Provider\IncompleteProfileProvider
    base.oauth_user_provider.class: BaseBundle\Security\Provider\OAuthUserProvider
    hwi_oauth.account.connector.class: BaseBundle\Connect\AccountConnect
    pagerfanta.view.light.class: BaseBundle\Pagerfanta\View\LightView
    pagerfanta.template.light.class: BaseBundle\Pagerfanta\Template\LightTemplate
    security.class: BaseBundle\Services\Security

services:

    base.incomplete_profile.service.provider:
        class: '%base.incomplete_profile.service.provider.class%'

    base.oauth_user_provider:
        class: '%base.oauth_user_provider.class%'
        parent: base.service
        arguments:
            - '@doctrine.orm.entity_manager'

    hwi_oauth.account.connector:
        class: '%hwi_oauth.account.connector.class%'

    pagerfanta.view.light:
        class: '%pagerfanta.view.light.class%'
        public: false
        arguments: ['@pagerfanta.template.light']
        tags:
            - { name: pagerfanta.view, alias: light }

    pagerfanta.template.light:
        class: '%pagerfanta.template.light.class%'
        public: false
        arguments: ['@translator']

    security:
        class: '%security.class%'
        arguments:
          - '@security.token_storage'
          - '@security.authorization_checker'
          - '@security.password_encoder'
          - '@security.authentication_utils'
          - '@security.role_hierarchy'
        calls:
          - [setContainer, ["@service_container"]]
